"""initial_schema

Revision ID: acd48066cb11
Revises: 
Create Date: 2026-05-31 09:03:01.278902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acd48066cb11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('knowledge_base_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_articles_category', 'knowledge_base_articles', ['category'], unique=False)
    op.create_index('idx_kb_articles_created_at', 'knowledge_base_articles', ['created_at'], unique=False)
    op.create_index('idx_kb_articles_created_by', 'knowledge_base_articles', ['created_by'], unique=False)
    op.create_index('idx_kb_articles_status', 'knowledge_base_articles', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_base_articles_category'), 'knowledge_base_articles', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_base_articles_created_at'), 'knowledge_base_articles', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_base_articles_created_by'), 'knowledge_base_articles', ['created_by'], unique=False)
    op.create_index(op.f('ix_knowledge_base_articles_id'), 'knowledge_base_articles', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_articles_status'), 'knowledge_base_articles', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_base_articles_title'), 'knowledge_base_articles', ['title'], unique=False)
    op.create_table('knowledge_base_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_submissions_created_at', 'knowledge_base_submissions', ['created_at'], unique=False)
    op.create_index('idx_kb_submissions_created_by', 'knowledge_base_submissions', ['created_by'], unique=False)
    op.create_index('idx_kb_submissions_status', 'knowledge_base_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_base_submissions_created_at'), 'knowledge_base_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_base_submissions_created_by'), 'knowledge_base_submissions', ['created_by'], unique=False)
    op.create_index(op.f('ix_knowledge_base_submissions_id'), 'knowledge_base_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_submissions_status'), 'knowledge_base_submissions', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('research_scope', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_project_name')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('raw_content', postgresql.BYTEA(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('included_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_project_id', 'reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('research_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(length=1000), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_research_sessions_project_id', 'research_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_sessions_id'), 'research_sessions', ['id'], unique=False)
    op.create_table('document_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_tables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index('idx_document_analyses_document_id', 'document_analyses', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_analyses_id'), 'document_analyses', ['id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_session_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('ARXIV', 'GOOGLE_SCHOLAR', 'SEMANTIC_SCHOLAR', 'WEB', name='search_source_enum'), nullable=False),
    sa.Column('search_type', sa.Enum('WEB', 'ACADEMIC', 'WIKIPEDIA', 'SEMANTIC', 'HYBRID', 'NEWS', 'CODE', name='search_type_enum'), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('retrieval_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_results_research_session_id', 'search_results', ['research_session_id'], unique=False)
    op.create_index(op.f('ix_search_results_id'), 'search_results', ['id'], unique=False)
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_embeddings')
    op.drop_index(op.f('ix_search_results_id'), table_name='search_results')
    op.drop_index('idx_search_results_research_session_id', table_name='search_results')
    op.drop_table('search_results')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_document_analyses_id'), table_name='document_analyses')
    op.drop_index('idx_document_analyses_document_id', table_name='document_analyses')
    op.drop_table('document_analyses')
    op.drop_index(op.f('ix_research_sessions_id'), table_name='research_sessions')
    op.drop_index('idx_research_sessions_project_id', table_name='research_sessions')
    op.drop_table('research_sessions')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index('idx_reports_project_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_knowledge_base_submissions_status'), table_name='knowledge_base_submissions')
    op.drop_index(op.f('ix_knowledge_base_submissions_id'), table_name='knowledge_base_submissions')
    op.drop_index(op.f('ix_knowledge_base_submissions_created_by'), table_name='knowledge_base_submissions')
    op.drop_index(op.f('ix_knowledge_base_submissions_created_at'), table_name='knowledge_base_submissions')
    op.drop_index('idx_kb_submissions_status', table_name='knowledge_base_submissions')
    op.drop_index('idx_kb_submissions_created_by', table_name='knowledge_base_submissions')
    op.drop_index('idx_kb_submissions_created_at', table_name='knowledge_base_submissions')
    op.drop_table('knowledge_base_submissions')
    op.drop_index(op.f('ix_knowledge_base_articles_title'), table_name='knowledge_base_articles')
    op.drop_index(op.f('ix_knowledge_base_articles_status'), table_name='knowledge_base_articles')
    op.drop_index(op.f('ix_knowledge_base_articles_id'), table_name='knowledge_base_articles')
    op.drop_index(op.f('ix_knowledge_base_articles_created_by'), table_name='knowledge_base_articles')
    op.drop_index(op.f('ix_knowledge_base_articles_created_at'), table_name='knowledge_base_articles')
    op.drop_index(op.f('ix_knowledge_base_articles_category'), table_name='knowledge_base_articles')
    op.drop_index('idx_kb_articles_status', table_name='knowledge_base_articles')
    op.drop_index('idx_kb_articles_created_by', table_name='knowledge_base_articles')
    op.drop_index('idx_kb_articles_created_at', table_name='knowledge_base_articles')
    op.drop_index('idx_kb_articles_category', table_name='knowledge_base_articles')
    op.drop_table('knowledge_base_articles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
